<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>AssetPilot.Infrastructure</AssemblyName>
    <GenerateAssemblyInfo>False</GenerateAssemblyInfo>
    <RootNamespace>AssetPilot.Infrastructure</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <ProjectReference Include="..\AssetPilot.Application\AssetPilot.Application.csproj" />
    <ProjectReference Include="..\AssetPilot.Domain\AssetPilot.Domain.csproj" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" />
    <PackageReference Include="SQLitePCLRaw.lib.e_sqlite3" />
  </ItemGroup>
</Project>
