import {FormEvent, useEffect, useState} from 'react'
import {api} from './api'

type Props={user:{role:string};onOpen:(id:number)=>void}
const managers=['admin','manager']
const assigners=['admin','manager','technician','team_lead']
const blank={asset_tag:'',name:'',hostname:'',serial_number:'',manufacturer:'',model:'',category:'Computer',asset_type:'Laptop',status:'Stock',condition:'Good',assigned_employee_id:'',location_id:'',department_id:'',purchase_date:'',purchase_cost:'',warranty_expiration:'',vendor:'',purpose:'',company:'',project:'',mac_address:'',notes:''}
const title=(value:string)=>value.replaceAll('_',' ').replace(/\b\w/g,c=>c.toUpperCase())
const when=(value:string)=>new Intl.DateTimeFormat(undefined,{dateStyle:'medium',timeStyle:'short'}).format(new Date(value))
function Badge({children,tone='neutral'}:{children:any;tone?:string}){return <span className={`badge ${tone}`}>{children}</span>}

export default function AssetInventory({user,onOpen}:Props){
 const [rows,setRows]=useState<any[]>([]),[summary,setSummary]=useState<any>(null),[metadata,setMetadata]=useState<any>({employees:[],departments:[],locations:[]})
 const [detail,setDetail]=useState<any>(null),[q,setQ]=useState(''),[loading,setLoading]=useState(false),[showForm,setShowForm]=useState(false),[editing,setEditing]=useState(false)
 const [form,setForm]=useState<any>(blank),[error,setError]=useState(''),[message,setMessage]=useState(''),[preview,setPreview]=useState<any>(null),[importing,setImporting]=useState(false)
 const canManage=managers.includes(user.role),canAssign=assigners.includes(user.role)
 function load(){Promise.all([api(`/assets?q=${encodeURIComponent(q)}`),api('/assets/summary'),api('/assets/metadata')]).then(([assets,totals,meta])=>{setRows(assets);setSummary(totals);setMetadata(meta)})}
 useEffect(load,[q])
 useEffect(()=>{if(canManage)api('/assets/import/assetpilot/preview').then(setPreview).catch(()=>{})},[])
 async function openRecord(id:number){setLoading(true);setDetail(await api(`/assets/${id}`));setLoading(false)}
 function startCreate(){setEditing(false);setForm(blank);setError('');setShowForm(true)}
 function startEdit(){setEditing(true);setForm({...blank,...detail,assigned_employee_id:detail.assigned_employee_id||'',location_id:detail.location_id||'',department_id:detail.department_id||'',purchase_cost:detail.purchase_cost_cents?String(detail.purchase_cost_cents/100):''});setError('');setShowForm(true)}
 async function save(e:FormEvent){e.preventDefault();setError('');const payload={...form,assigned_employee_id:form.assigned_employee_id?+form.assigned_employee_id:null,location_id:form.location_id?+form.location_id:null,department_id:form.department_id?+form.department_id:null,purchase_cost_cents:form.purchase_cost?Math.round(+form.purchase_cost*100):null,purchase_date:form.purchase_date||null,warranty_expiration:form.warranty_expiration||null};delete payload.purchase_cost;try{if(editing){await api(`/assets/${detail.id}`,{method:'PATCH',body:JSON.stringify(payload)});await openRecord(detail.id)}else{const created=await api('/assets',{method:'POST',body:JSON.stringify(payload)});await openRecord(created.id)}setShowForm(false);load()}catch(e:any){setError(e.message)}}
 async function assign(employeeId:string){await api(`/assets/${detail.id}/assign`,{method:'POST',body:JSON.stringify({employee_id:employeeId?+employeeId:null,status:employeeId?'Active':'Stock'})});await openRecord(detail.id);load()}
 async function archive(){await api(`/assets/${detail.id}`,{method:'PATCH',body:JSON.stringify({is_archived:true,status:'Retired'})});setDetail(null);load()}
 async function importAssetPilot(){if(!confirm(`Import ${preview?.counts?.Assets||0} AssetPilot assets and ${preview?.counts?.Employees||0} employees into this inventory? Existing matches will be updated.`))return;setImporting(true);setMessage('');setError('');try{const result=await api('/assets/import/assetpilot',{method:'POST'});setMessage(`Imported ${result.assets_created} new assets and updated ${result.assets_updated}. ${result.employees_created} employees were added.`);load()}catch(e:any){setError(e.message)}finally{setImporting(false)}}
 return <>
  <section className="page-intro inventory-intro"><div><p className="eyebrow">Unified asset inventory</p><h2>Assets and service work in one place</h2><p>Add and maintain equipment here, assign it to employees, and connect it directly to support tickets. AssetPilot records are now part of this inventory and can be refreshed safely if the old database changes.</p></div><div className="inventory-actions">{user.role==='admin'&&preview&&<button onClick={importAssetPilot} disabled={importing}>{importing?'Refreshing…':preview.imported_assets>=preview.counts.Assets?`Refresh AssetPilot (${preview.imported_assets})`:`Import AssetPilot (${preview.counts.Assets})`}</button>}{canManage&&<button className="primary" onClick={startCreate}>Add asset</button>}</div></section>
  {message&&<div className="alert success">{message}</div>}{error&&<div className="alert danger">{error}</div>}
  {summary&&<div className="inventory-summary"><article><span>Total assets</span><strong>{summary.total}</strong></article><article><span>Assigned</span><strong>{summary.assigned}</strong></article><article><span>Available stock</span><strong>{summary.unassigned}</strong></article><article><span>Warranty due ≤90 days</span><strong>{summary.warranty_expiring}</strong></article><div><Badge tone="on_track">{summary.integration_status}</Badge><small>{summary.inventory_source} · {summary.archived} archived</small></div></div>}
  <div className="inventory-filter"><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search asset tag, hostname, or serial number…"/><span>{rows.length} matching assets</span></div>
  <div className={`directory-layout ${detail?'with-detail':''}`}><div className="data-table"><table><thead><tr>{['Asset','Type','Manufacturer / model','Assigned to','Location','Status'].map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{rows.map(r=><tr className={detail?.id===r.id?'selected':''} key={r.id} onClick={()=>openRecord(r.id)}><td><strong>{r.asset_tag}</strong><small>{r.hostname||r.serial_number||r.name||'No device identifier'}</small></td><td>{r.asset_type}</td><td>{r.manufacturer} {r.model}</td><td>{r.assigned_employee||'Available stock'}</td><td>{r.location||'—'}</td><td><Badge tone={r.status==='Active'?'on_track':'neutral'}>{r.status}</Badge></td></tr>)}</tbody></table></div>
  {loading?<aside className="record-detail"><div className="loading">Loading record…</div></aside>:detail&&<aside className="record-detail asset-detail"><button className="close-detail" onClick={()=>setDetail(null)}>×</button><p className="eyebrow">{detail.source} inventory record</p><h2>{detail.asset_tag}</h2><p className="muted">{detail.name||`${detail.manufacturer} ${detail.model}`}</p>{canManage&&<div className="detail-actions"><button onClick={startEdit}>Edit asset</button><button className="danger-action" onClick={archive}>Retire</button></div>}
   <div className="record-facts"><div><span>Hostname</span><strong>{detail.hostname||'Not assigned'}</strong></div><div><span>Serial number</span><strong>{detail.serial_number||'Not recorded'}</strong></div><div><span>Type / category</span><strong>{detail.asset_type} · {detail.category}</strong></div><div><span>Condition</span><strong>{detail.condition}</strong></div><div><span>Location</span><strong>{detail.location||'Not recorded'}</strong></div><div><span>Warranty expires</span><strong>{detail.warranty_expiration||'Not recorded'}</strong></div></div>
   <h3>Assignment</h3><p className="muted">{detail.employee?`${detail.employee.name} · ${detail.employee.email}`:'This asset is available stock.'}</p>{canAssign&&<div className="assignment-control"><select defaultValue={detail.assigned_employee_id||''} key={detail.assigned_employee_id||'none'} onChange={e=>assign(e.target.value)}><option value="">Return to available stock</option>{metadata.employees.map((e:any)=><option value={e.id} key={e.id}>{e.name} · {e.employee_number}</option>)}</select></div>}
   <h3>Related tickets</h3>{detail.tickets.length?<div className="mini-list">{detail.tickets.map((t:any)=><button key={t.id} onClick={()=>onOpen(t.id)}><strong>{t.number} · {t.subject}</strong><span>{t.status} · {t.priority}</span></button>)}</div>:<p className="muted">No tickets linked to this asset.</p>}
   <h3>Lifecycle history</h3><div className="history-list">{detail.history.slice(0,12).map((h:any)=><div key={h.id}><span>●</span><p><strong>{title(h.event_type)}</strong><small>{when(h.created_at)}</small></p></div>)}</div>
  </aside>}</div>
  {showForm&&<div className="modal-layer"><form className="modal asset-form" onSubmit={save}><button type="button" className="modal-close" onClick={()=>setShowForm(false)}>×</button><p className="eyebrow">{editing?'Update inventory record':'New inventory record'}</p><h2>{editing?`Edit ${detail.asset_tag}`:'Add an asset'}</h2>{error&&<div className="alert danger">{error}</div>}<div className="asset-form-grid">
   <label>Asset tag<input required value={form.asset_tag} onChange={e=>setForm({...form,asset_tag:e.target.value})}/></label><label>Display name<input value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></label><label>Hostname<input value={form.hostname||''} onChange={e=>setForm({...form,hostname:e.target.value||null})}/></label><label>Serial number<input value={form.serial_number||''} onChange={e=>setForm({...form,serial_number:e.target.value||null})}/></label>
   <label>Asset type<input required value={form.asset_type} onChange={e=>setForm({...form,asset_type:e.target.value})}/></label><label>Category<input value={form.category} onChange={e=>setForm({...form,category:e.target.value})}/></label><label>Manufacturer<input value={form.manufacturer} onChange={e=>setForm({...form,manufacturer:e.target.value})}/></label><label>Model<input value={form.model} onChange={e=>setForm({...form,model:e.target.value})}/></label>
   <label>Status<select value={form.status} onChange={e=>setForm({...form,status:e.target.value})}>{['Stock','Active','Loaned','Repair','Lost','Retired'].map(x=><option key={x}>{x}</option>)}</select></label><label>Condition<select value={form.condition} onChange={e=>setForm({...form,condition:e.target.value})}>{['New','Good','Fair','Poor','Damaged'].map(x=><option key={x}>{x}</option>)}</select></label><label>Assigned employee<select value={form.assigned_employee_id} onChange={e=>setForm({...form,assigned_employee_id:e.target.value})}><option value="">Available stock</option>{metadata.employees.map((e:any)=><option value={e.id} key={e.id}>{e.name}</option>)}</select></label><label>Location<select value={form.location_id} onChange={e=>setForm({...form,location_id:e.target.value})}><option value="">Not recorded</option>{metadata.locations.map((x:any)=><option value={x.id} key={x.id}>{x.name}</option>)}</select></label>
   <label>Department<select value={form.department_id} onChange={e=>setForm({...form,department_id:e.target.value})}><option value="">Not recorded</option>{metadata.departments.map((x:any)=><option value={x.id} key={x.id}>{x.name}</option>)}</select></label><label>Vendor<input value={form.vendor||''} onChange={e=>setForm({...form,vendor:e.target.value||null})}/></label><label>Purchase date<input type="date" value={form.purchase_date||''} onChange={e=>setForm({...form,purchase_date:e.target.value})}/></label><label>Purchase cost ($)<input type="number" min="0" step="0.01" value={form.purchase_cost} onChange={e=>setForm({...form,purchase_cost:e.target.value})}/></label><label>Warranty expiration<input type="date" value={form.warranty_expiration||''} onChange={e=>setForm({...form,warranty_expiration:e.target.value})}/></label><label>MAC address<input value={form.mac_address||''} onChange={e=>setForm({...form,mac_address:e.target.value||null})}/></label><label className="wide">Purpose<input value={form.purpose||''} onChange={e=>setForm({...form,purpose:e.target.value||null})}/></label><label className="wide">Notes<textarea rows={3} value={form.notes||''} onChange={e=>setForm({...form,notes:e.target.value})}/></label>
  </div><div className="form-actions"><button type="button" onClick={()=>setShowForm(false)}>Cancel</button><button className="primary">{editing?'Save changes':'Add asset'}</button></div></form></div>}
 </>
}
