import {useMemo,useState} from 'react'

type Props={data:any;asset:any;onClose:()=>void}
const bytes=(value:any,digits=1)=>{const n=Number(value);if(!Number.isFinite(n)||n<=0)return 'Unavailable';const units=['B','KB','MB','GB','TB'];const i=Math.min(Math.floor(Math.log(n)/Math.log(1024)),units.length-1);return `${(n/1024**i).toFixed(i?digits:0)} ${units[i]}`}
const dateTime=(value:any)=>{if(!value)return 'Unavailable';const d=new Date(value);return Number.isNaN(d.getTime())?'Unavailable':new Intl.DateTimeFormat(undefined,{dateStyle:'medium',timeStyle:'short'}).format(d)}
const age=(value:any)=>{if(!value)return 'Unavailable';const seconds=Math.max(0,Math.floor((Date.now()-new Date(value).getTime())/1000));if(seconds<60)return 'Just now';if(seconds<3600)return `${Math.floor(seconds/60)}m ago`;if(seconds<86400)return `${Math.floor(seconds/3600)}h ago`;return `${Math.floor(seconds/86400)}d ago`}
const uptime=(value:any)=>{if(!value)return 'Unavailable';const bootTime=new Date(value).getTime();if(Number.isNaN(bootTime))return 'Unavailable';const seconds=Math.max(0,Math.floor((Date.now()-bootTime)/1000));const days=Math.floor(seconds/86400),hours=Math.floor(seconds%86400/3600),mins=Math.floor(seconds%3600/60);return `${days?`${days}d `:''}${hours}h ${mins}m`}
const statusText=(value:any,yes='Enabled',no='Disabled')=>value===true||value===1?yes:value===false||value===0?no:typeof value==='string'&&value?value:'Unavailable'
const tone=(value:any)=>{const text=String(value||'').toLowerCase();if(['healthy','enabled','ready','yes','no','online','active','joined'].some(x=>text===x||text.includes(x)))return 'good';if(['unhealthy','disabled','attention','error','conflict'].some(x=>text.includes(x)))return 'bad';return 'neutral'}
function Status({children}:{children:any}){const value=children??'Unavailable';return <span className={`di-status ${tone(value)}`}>{String(value)}</span>}
function Row({label,value,status=false}:{label:string;value:any;status?:boolean}){return <div className="di-row"><span>{label}</span><strong>{status?<Status>{value}</Status>:value??'Unavailable'}</strong></div>}

export default function DeviceIntelligence({data,asset,onClose}:Props){
 const [softwareQuery,setSoftwareQuery]=useState('')
 const inventory=data?.inventory||{},agent=data?.agent||{},device=inventory.device||{},os=inventory.os||{},cpu=inventory.cpu||{},memory=inventory.memory||{},storage=inventory.storage||{},security=inventory.security||{},management=inventory.management||{},battery=inventory.battery||{}
 const volumes=Array.isArray(storage.volumes)?storage.volumes:[],disks=Array.isArray(storage.physical_disks)?storage.physical_disks:[],adapters=Array.isArray(inventory.network?.adapters)?inventory.network.adapters:[],gpus=Array.isArray(inventory.gpu)?inventory.gpu:[],modules=Array.isArray(memory.modules)?memory.modules:[]
 const software=useMemo(()=>{const q=softwareQuery.trim().toLowerCase();return (Array.isArray(inventory.software)?inventory.software:[]).filter((item:any)=>!q||[item.name,item.version,item.publisher].some(v=>String(v||'').toLowerCase().includes(q)))},[inventory.software,softwareQuery])
 const primary=volumes[0]||{},defender=security.defender||{},firewall=Array.isArray(security.firewall)?security.firewall:[]
 const encryption=typeof security.encryption==='string'?security.encryption:(Array.isArray(security.encryption)&&security.encryption.length?security.encryption.map((x:any)=>x.protection_status||x.volume_status).join(', '):'Unavailable')
 const tpm=security.tpm||{},tpmState=tpm.ready===true?'Ready':tpm.present===false?'Not Present':tpm.present===true?'Present, Not Ready':'Unavailable'
 const health=inventory.health?.status||'Unknown',securityHealth=defender.antivirus_enabled===true&&firewall.every((x:any)=>x.enabled===true||x.enabled===1)?'Healthy':'Review'
 return <div className="device-intelligence-layer" role="dialog" aria-modal="true" aria-label="Device Intelligence"><div className="device-intelligence">
  <header><div><p className="eyebrow">Managed Windows endpoint</p><h2>Device Intelligence</h2><p>{device.hostname||asset.hostname||asset.asset_tag} · {device.manufacturer||asset.manufacturer} {device.model||asset.model}</p></div><div className="di-header-actions"><span><i></i>{agent.status||'Unknown'}</span><button onClick={onClose} aria-label="Close Device Intelligence">×</button></div></header>
  <div className="di-freshness"><strong>Latest persisted inventory</strong><span>Collected {age(agent.last_inventory_at||inventory.collected_at)} · Agent {agent.agent_version||inventory.agent_version||'Unknown'}</span></div>
  <section className="di-summary">
   <article><span>Overall health</span><strong><Status>{health}</Status></strong><small>{inventory.health?.unknown_count||0} checks unavailable</small></article>
   <article><span>CPU</span><strong>{cpu.utilization_percent??'—'}%</strong><small>{cpu.model||'Unavailable'}</small></article>
   <article><span>Memory</span><strong>{bytes(memory.used_bytes)} / {bytes(memory.total_bytes)}</strong><small>{memory.percent_used??'—'}% used · {bytes(memory.available_bytes)} available</small></article>
   <article><span>Storage</span><strong>{bytes(primary.free_bytes)} free</strong><small>of {bytes(primary.total_bytes)}</small></article>
   <article><span>Security</span><strong><Status>{securityHealth}</Status></strong><small>Encryption · Defender · Firewall</small></article>
   <article><span>Last inventory</span><strong>{age(agent.last_inventory_at||inventory.collected_at)}</strong><small>{dateTime(agent.last_inventory_at||inventory.collected_at)}</small></article>
  </section>
  <div className="di-two-column">
   <section className="di-card"><h3>Overview</h3><Row label="Hostname" value={device.hostname}/><Row label="Manufacturer" value={device.manufacturer}/><Row label="Model" value={device.model}/><Row label="Serial Number" value={device.serial_number}/><Row label="Windows" value={os.edition}/><Row label="Version" value={os.version}/><Row label="Build" value={os.build}/><Row label="Architecture" value={os.architecture}/><Row label="Last Boot" value={dateTime(os.last_boot)}/><Row label="Uptime" value={uptime(os.last_boot)}/><Row label="Assigned User" value={asset.employee?.email||agent.observed_user_email||'Unassigned'}/></section>
   <section className="di-card"><h3>Performance</h3><Row label="CPU" value={cpu.model}/><Row label="Cores / Threads" value={`${cpu.physical_cores??'—'} / ${cpu.logical_processors??'—'}`}/><Row label="CPU Utilization" value={cpu.utilization_percent!=null?`${cpu.utilization_percent}%`:'Unavailable'}/><Row label="Memory" value={`${bytes(memory.total_bytes)} total`}/><Row label="Memory Used" value={`${bytes(memory.used_bytes)} (${memory.percent_used??'—'}%)`}/><Row label="Memory Available" value={bytes(memory.available_bytes)}/><Row label="Battery" value={battery.present?`${battery.percentage??'—'}% (${battery.status||'Unknown'})`:'Not Present'}/><Row label="Assignment Check" value={agent.assignment_state||'Unknown'} status/></section>
  </div>
  <div className="di-two-column">
   <section className="di-card"><h3>Security</h3><Row label="BitLocker / Device Encryption" value={encryption} status/><Row label="TPM" value={tpmState} status/><Row label="Secure Boot" value={security.secure_boot||'Unavailable'} status/><Row label="Defender" value={defender.antivirus_enabled===true?'Healthy':defender.antivirus_enabled===false?'Disabled':'Unavailable'} status/>{firewall.map((item:any)=><Row key={item.profile} label={`Firewall (${item.profile})`} value={statusText(item.enabled)} status/>)}<Row label="Pending Reboot" value={security.pending_reboot||'Unknown'} status/></section>
   <section className="di-card"><h3>Management</h3><Row label="Domain / Workgroup" value={management.domain_joined?`Domain: ${management.domain_name||'Unknown'}`:`Workgroup: ${management.workgroup||'Unknown'}`}/><Row label="Domain Joined" value={management.domain_joined?'Yes':'No'} status/><Row label="Entra (Azure AD) Joined" value={management.entra_joined||'Unknown'} status/><Row label="Workplace Joined" value={management.workplace_joined||'Unknown'} status/><Row label="MDM / Intune" value={management.mdm_status||'Unavailable'} status/><Row label="BIOS" value={`${inventory.bios?.vendor||''} ${inventory.bios?.version||'Unavailable'}`.trim()}/><Row label="Firmware Mode" value={inventory.bios?.firmware_mode||'Unavailable'} status/></section>
  </div>
  <section className="di-card"><h3>Storage</h3><div className="di-table"><table><thead><tr><th>Drive</th><th>Label</th><th>FS</th><th>Total</th><th>Free</th><th>% Free</th></tr></thead><tbody>{volumes.map((v:any,i:number)=><tr key={`${v.drive}-${i}`}><td>{v.drive}</td><td>{v.label||'—'}</td><td>{v.filesystem||'—'}</td><td>{bytes(v.total_bytes)}</td><td>{bytes(v.free_bytes)}</td><td>{v.percent_free??'—'}%</td></tr>)}</tbody></table></div><h4>Physical disks</h4><div className="di-table"><table><thead><tr><th>Model</th><th>Type</th><th>Size</th><th>Health</th></tr></thead><tbody>{disks.map((d:any,i:number)=><tr key={i}><td>{d.model||'Unknown'}</td><td>{[d.bus_type,d.media_type].filter(Boolean).join(' ')||'Unknown'}</td><td>{bytes(d.size_bytes)}</td><td><Status>{d.health||'Unknown'}</Status></td></tr>)}</tbody></table></div></section>
  <section className="di-card"><h3>Network</h3><div className="di-table"><table><thead><tr><th>Adapter</th><th>Type</th><th>MAC</th><th>IPv4</th><th>Gateway</th></tr></thead><tbody>{adapters.map((a:any,i:number)=><tr key={i}><td>{a.description||a.name} <Status>{a.state||'Unknown'}</Status></td><td>{a.type||'Unknown'}</td><td>{a.mac_address||'Unavailable'}</td><td>{(a.ipv4||[]).filter(Boolean).join(', ')||'Unavailable'}</td><td>{(a.gateway||[]).filter(Boolean).join(', ')||'Unavailable'}</td></tr>)}</tbody></table></div></section>
  <section className="di-card"><h3>Hardware</h3>{gpus.map((g:any,i:number)=><Row key={i} label={g.name||`GPU ${i+1}`} value={Number(g.adapter_ram_bytes||0)<=1024**3?'Integrated / shared memory':`${bytes(g.adapter_ram_bytes)} dedicated`}/>)}<Row label="Displays" value={inventory.peripherals?.displays?.length??'Unavailable'}/><Row label="Printers" value={inventory.peripherals?.printers?.length??'Unavailable'}/><Row label="Audio Devices" value={inventory.peripherals?.audio_devices?.length??'Unavailable'}/><Row label="Bluetooth Adapters" value={inventory.peripherals?.bluetooth_adapters?.length??'Unavailable'}/><Row label="Memory Modules" value={modules.length||'Unavailable'}/>{modules.length>0&&<details><summary>Show module details</summary>{modules.map((m:any,i:number)=><p key={i}>{m.slot||`Slot ${i+1}`} · {bytes(m.capacity_bytes)} · {m.speed_mhz||'—'} MHz · {m.manufacturer||'Unknown'} {m.part_number||''}</p>)}</details>}</section>
  <section className="di-card di-software"><div className="di-section-heading"><div><h3>Installed Software</h3><p>{software.length} of {(inventory.software||[]).length} applications</p></div><input value={softwareQuery} onChange={e=>setSoftwareQuery(e.target.value)} placeholder="Search software…"/></div><div className="di-table"><table><thead><tr><th>Name</th><th>Version</th><th>Publisher</th><th>Installed</th></tr></thead><tbody>{software.map((item:any,i:number)=><tr key={`${item.name}-${item.version}-${i}`}><td>{item.name}</td><td>{item.version||'—'}</td><td>{item.publisher||'—'}</td><td>{item.install_date||'—'}</td></tr>)}</tbody></table></div></section>
 </div></div>
}
