import {DragEvent, FormEvent, useEffect, useMemo, useRef, useState} from 'react'
import {api} from './api'
import './incident-form.css'

type User={id:number;display_name:string;email:string;role:string}
type Option={key:string;name:string;active?:boolean}
type Category={id:number;name:string;parent_id:number|null;level:string}
type Lookup={id:number;display_name:string;email:string;department?:string;location?:string;employee_id?:string}

const draftKey='northstar-new-incident-draft'
const requestId=()=>`${Date.now()}_${crypto.randomUUID().replaceAll('-','')}`

function SearchSelect({label,value,options,onChange,required=false,disabled=false,help}:{label:string;value:string;options:{value:string;label:string;meta?:string}[];onChange:(value:string)=>void;required?:boolean;disabled?:boolean;help?:string}){
 const [query,setQuery]=useState(''),[open,setOpen]=useState(false)
 const selected=options.find(option=>option.value===value)
 const filtered=options.filter(option=>`${option.label} ${option.meta||''}`.toLowerCase().includes(query.toLowerCase())).slice(0,40)
 return <label className="incident-field"><span>{label}{required&&<b> *</b>}</span><div className="search-select"><input aria-label={label} disabled={disabled} required={required} value={open?query:(selected?.label||'')} onFocus={()=>{setOpen(true);setQuery('')}} onChange={event=>{setQuery(event.target.value);setOpen(true)}} placeholder={`Search ${label.toLowerCase()}…`}/>{open&&!disabled&&<div className="search-options" role="listbox">{filtered.length?filtered.map(option=><button type="button" role="option" aria-selected={option.value===value} key={option.value} onMouseDown={event=>event.preventDefault()} onClick={()=>{onChange(option.value);setOpen(false);setQuery('')}}><strong>{option.label}</strong>{option.meta&&<small>{option.meta}</small>}</button>):<p>No matching options</p>}</div>}</div>{help&&<small>{help}</small>}</label>
}

export default function IncidentForm({user,bootstrap,onDone,onCancel}:{user:User;bootstrap:any;onDone:(id:number)=>void;onCancel:()=>void}){
 const [config,setConfig]=useState<any>(null),[loading,setLoading]=useState(true),[error,setError]=useState(''),[errors,setErrors]=useState<Record<string,string>>({}),[busy,setBusy]=useState(false)
 const [requesterResults,setRequesterResults]=useState<Lookup[]>([]),[requester,setRequester]=useState<Lookup|null>(null),[assets,setAssets]=useState<any[]>([]),[technicians,setTechnicians]=useState<any[]>([]),[files,setFiles]=useState<File[]>([])
 const [form,setForm]=useState<any>({client_request_id:requestId(),request_type:'Incident',status:'Open',mode:'Web Form',level:'Tier 1',impact:'Medium',impact_details:'',urgency:'Medium',priority_override:'',priority_override_reason:'',requester_id:user.id,site_location:'',asset_ids:[],configuration_item_ids:[],team_id:'',assigned_user_id:'',category_id:'',subcategory_id:'',item_id:'',subject:'',description:'',emails_to_notify:'',resolution:''})
 const [priority,setPriority]=useState<any>(null),dirty=useRef(false),fileInput=useRef<HTMLInputElement>(null)
 useEffect(()=>{api('/incidents/config').then(data=>{setConfig(data);setRequester(data.requester);setRequesterResults([data.requester]);const saved=localStorage.getItem(draftKey);if(saved)try{setForm((current:any)=>({...current,...JSON.parse(saved),client_request_id:requestId()}))}catch{} }).catch(e=>setError(e.message)).finally(()=>setLoading(false))},[])
 useEffect(()=>{const warning=(event:BeforeUnloadEvent)=>{if(dirty.current){event.preventDefault();event.returnValue=''}};addEventListener('beforeunload',warning);return()=>removeEventListener('beforeunload',warning)},[])
 useEffect(()=>{if(!config)return;api(`/incidents/priority-preview?impact=${encodeURIComponent(form.impact)}&urgency=${encodeURIComponent(form.urgency)}`).then(setPriority).catch(()=>{})},[config,form.impact,form.urgency])
 useEffect(()=>{if(!requester)return;api(`/lookups/assets?requester_id=${requester.id}`).then(setAssets);setForm((current:any)=>({...current,requester_id:requester.id,on_behalf_of_id:requester.id===user.id?null:requester.id,site_location:requester.location||'',asset_ids:[]}))},[requester?.id])
 useEffect(()=>{if(!form.team_id){setTechnicians([]);return}api(`/lookups/technicians?team_id=${form.team_id}&site=${encodeURIComponent(form.site_location||'')}`).then(setTechnicians).catch(()=>setTechnicians([]))},[form.team_id,form.site_location])
 const taxonomy=config?.taxonomy||{},active=(key:string)=>(taxonomy[key]||[]).filter((item:Option)=>item.active!==false)
 const categories:Category[]=config?.categories||[],top=categories.filter(item=>!item.parent_id),subs=categories.filter(item=>item.parent_id===+form.category_id),items=categories.filter(item=>item.parent_id===+form.subcategory_id)
 const selectedCategory=top.find(item=>item.id===+form.category_id)
 const update=(changes:any)=>{dirty.current=true;setForm((current:any)=>({...current,...changes}))}
 async function searchRequesters(query:string){if(!config?.permissions.submit_on_behalf)return;setRequesterResults(await api(`/lookups/users?q=${encodeURIComponent(query)}`))}
 function addFiles(next:File[]){const allowed=next.filter(file=>file.size<=25*1024*1024);setFiles(current=>[...current,...allowed].slice(0,10));dirty.current=true}
 function drop(event:DragEvent){event.preventDefault();addFiles(Array.from(event.dataTransfer.files))}
 function validate(){const next:Record<string,string>={};if(!requester)next.requester='Choose a requester.';if(!form.category_id)next.category='Choose a category.';if(form.subcategory_id&&!subs.some(item=>item.id===+form.subcategory_id))next.category='Choose a valid category and subcategory.';if(form.item_id&&!items.some(item=>item.id===+form.item_id))next.category='Choose a valid item.';if(form.subject.trim().length<4)next.subject='Enter a subject with at least 4 characters.';if(form.description.trim().length<10)next.description='Enter at least 10 characters describing the incident.';const emails=form.emails_to_notify.split(',').map((value:string)=>value.trim()).filter(Boolean);if(emails.some((value:string)=>!/^[^@\s]+@[^@\s]+\.[^@\s]+$/.test(value)))next.emails='Enter valid email addresses separated by commas.';if(form.priority_override&&form.priority_override!==priority?.priority&&!form.priority_override_reason.trim())next.priority='Explain the priority override.';setErrors(next);return !Object.keys(next).length}
 async function submit(event:FormEvent){event.preventDefault();if(busy||!validate())return;setBusy(true);setError('');try{const payload={...form,requester_id:requester!.id,on_behalf_of_id:requester!.id===user.id?null:requester!.id,category_id:+form.category_id,subcategory_id:form.subcategory_id?+form.subcategory_id:null,item_id:form.item_id?+form.item_id:null,team_id:form.team_id?+form.team_id:null,assigned_user_id:form.assigned_user_id?+form.assigned_user_id:null,priority_override:form.priority_override||null,priority_override_reason:form.priority_override_reason||null,emails_to_notify:form.emails_to_notify.split(',').map((value:string)=>value.trim()).filter(Boolean),form_definition_id:config.default_form?.id,custom_data:{resolution_draft:form.resolution||''}};delete payload.resolution;const result=await api('/incidents',{method:'POST',body:JSON.stringify(payload)});if(files.length){const body=new FormData();files.forEach(file=>body.append('files',file));await api(`/incidents/${result.ticket.id}/attachments`,{method:'POST',body})}dirty.current=false;localStorage.removeItem(draftKey);onDone(result.ticket.id)}catch(e:any){setError(e.message)}finally{setBusy(false)}}
 function saveDraft(){localStorage.setItem(draftKey,JSON.stringify(form));dirty.current=false;setError('Draft saved in this browser. It has not been submitted or published.')}
 function reset(){if(dirty.current&&!confirm('Reset every field in this incident?'))return;localStorage.removeItem(draftKey);setForm({...form,client_request_id:requestId(),impact:'Medium',urgency:'Medium',request_type:'Incident',status:'Open',mode:'Web Form',level:'Tier 1',impact_details:'',priority_override:'',priority_override_reason:'',asset_ids:[],team_id:'',assigned_user_id:'',category_id:'',subcategory_id:'',item_id:'',subject:'',description:'',emails_to_notify:'',resolution:''});setFiles([]);setErrors({});dirty.current=false}
 const option=(items:Option[])=>items.map(item=>({value:item.name,label:item.name}))
 if(loading)return <div className="loading">Preparing the incident form…</div>
 if(!config)return <div className="alert danger">{error||'Incident configuration is unavailable.'}</div>
 return <section className="incident-shell"><header className="incident-hero"><div><p className="eyebrow">Incident management</p><h2>New Incident</h2><p>Report an interruption or degraded service. Required information is used for priority, routing, and SLA selection.</p></div><aside><strong>Secure submission</strong><span>Drafts stay in this browser</span><small>Priority and routing are explained before and after submission</small></aside></header>{error&&<div className={error.startsWith('Draft saved')?'alert success':'alert danger'}>{error}</div>}<form onSubmit={submit} noValidate>
  <section className="incident-section"><header><span>1</span><div><h3>Classification</h3><p>Describe the type, source, and business effect.</p></div></header><div className="incident-grid">
   <SearchSelect label="Request Type" required value={form.request_type} options={option(active('request_types'))} onChange={value=>update({request_type:value})}/><SearchSelect label="Status" required value={form.status} options={option(active('statuses'))} onChange={value=>update({status:value})}/><SearchSelect label="Mode / Source" required value={form.mode} options={option(active('modes'))} onChange={value=>update({mode:value})}/><SearchSelect label="Level" required value={form.level} options={option(active('levels'))} onChange={value=>update({level:value})}/><SearchSelect label="Impact" required value={form.impact} options={option(active('impacts'))} onChange={value=>update({impact:value})}/><SearchSelect label="Urgency" required value={form.urgency} options={option(active('urgencies'))} onChange={value=>update({urgency:value})}/><label className="incident-field span-2"><span>Impact Details</span><textarea rows={3} maxLength={4000} value={form.impact_details} onChange={e=>update({impact_details:e.target.value})} placeholder="Explain affected users, services, locations, deadlines, or safety concerns without adding sensitive medical information."/></label>
   <div className="priority-card"><span>Calculated priority</span><strong>{priority?.priority||'Calculating…'}</strong><p>{priority?.reason}</p><small>{priority?.sla_reason}</small></div>{config.permissions.override_priority&&<><SearchSelect label="Override Priority" value={form.priority_override} options={[{value:'',label:'Use calculated priority'},...option(active('priorities'))]} onChange={value=>update({priority_override:value})}/>{form.priority_override&&form.priority_override!==priority?.priority&&<label className="incident-field"><span>Override reason <b>*</b></span><input value={form.priority_override_reason} onChange={e=>update({priority_override_reason:e.target.value})}/>{errors.priority&&<em>{errors.priority}</em>}</label>}</>}
  </div></section>
  <section className="incident-section"><header><span>2</span><div><h3>Requester and asset context</h3><p>Profile and assigned equipment are derived from the requester.</p></div></header><div className="incident-grid">
   <label className="incident-field span-2"><span>Requester <b>*</b></span>{config.permissions.submit_on_behalf&&<input aria-label="Search requester" onChange={e=>searchRequesters(e.target.value)} placeholder="Search by name or email…"/>}<select aria-label="Requester" required value={requester?.id||''} onChange={e=>setRequester(requesterResults.find(item=>item.id===+e.target.value)||null)}>{requesterResults.map(item=><option value={item.id} key={item.id}>{item.display_name} · {item.email}</option>)}</select>{requester?.id!==user.id&&<small>Submitted on behalf of {requester?.display_name}. The requester owns the incident and receives updates.</small>}{errors.requester&&<em>{errors.requester}</em>}</label><div className="derived-card"><span>Department</span><strong>{requester?.department||'Not recorded'}</strong><small>Derived from requester profile</small></div><label className="incident-field"><span>Site / Location</span><input value={form.site_location} readOnly={!config.permissions.submit_on_behalf} onChange={e=>update({site_location:e.target.value})}/><small>{config.permissions.submit_on_behalf?'Requester-derived; authorized staff may override.':'Derived from your profile.'}</small></label>
   <fieldset className="asset-picker span-3"><legend>Assets</legend>{assets.length?assets.map(asset=><label className={form.asset_ids.includes(asset.id)?'selected':''} key={asset.id}><input type="checkbox" checked={form.asset_ids.includes(asset.id)} onChange={()=>update({asset_ids:form.asset_ids.includes(asset.id)?form.asset_ids.filter((id:number)=>id!==asset.id):[...form.asset_ids,asset.id]})}/><span><strong>{asset.hostname||asset.asset_tag}</strong><small>{asset.device_type} · {asset.asset_tag} · {asset.location||'Location not recorded'}</small></span></label>):<p>No active asset assignment matches this requester’s email.</p>}</fieldset>
  </div></section>
  {config.permissions.assign&&<section className="incident-section"><header><span>3</span><div><h3>Assignment</h3><p>Leave blank for automatic rule-based routing.</p></div></header><div className="incident-grid"><SearchSelect label="Assignment Group" value={String(form.team_id)} options={[{value:'',label:'Route automatically'},...config.teams.map((team:any)=>({value:String(team.id),label:team.name,meta:team.region}))]} onChange={value=>update({team_id:value,assigned_user_id:''})}/><SearchSelect label="Technician / Assignee" value={String(form.assigned_user_id)} disabled={!form.team_id} options={[{value:'',label:'Assign automatically'},...technicians.map((tech:any)=>({value:String(tech.id),label:tech.display_name,meta:`${tech.email} · ${tech.availability}`}))]} onChange={value=>update({assigned_user_id:value})}/><div className="routing-reason"><span>Routing preview</span><strong>{form.team_id?'Manual assignment will be recorded.':selectedCategory?`Rules will evaluate Category = ${selectedCategory.name}.`:'Choose a category to explain automatic routing.'}</strong><small>The incident timeline records every rule evaluated and why the final group was chosen.</small></div></div></section>}
  <section className="incident-section"><header><span>{config.permissions.assign?'4':'3'}</span><div><h3>Categorization</h3><p>Subcategory and item choices depend on the parent selection.</p></div></header><div className="incident-grid"><SearchSelect label="Category" required value={String(form.category_id)} options={top.map(item=>({value:String(item.id),label:item.name}))} onChange={value=>update({category_id:value,subcategory_id:'',item_id:''})}/><SearchSelect label="Subcategory" value={String(form.subcategory_id)} disabled={!form.category_id||!subs.length} options={[{value:'',label:subs.length?'Choose subcategory':'No subcategories configured'},...subs.map(item=>({value:String(item.id),label:item.name}))]} onChange={value=>update({subcategory_id:value,item_id:''})}/><SearchSelect label="Item" value={String(form.item_id)} disabled={!form.subcategory_id||!items.length} options={[{value:'',label:items.length?'Choose item':'No items configured'},...items.map(item=>({value:String(item.id),label:item.name}))]} onChange={value=>update({item_id:value})}/>{errors.category&&<em className="span-3 field-error">{errors.category}</em>}</div></section>
  <section className="incident-section"><header><span>{config.permissions.assign?'5':'4'}</span><div><h3>Request details</h3><p>Give the service desk enough information to begin work.</p></div></header><div className="incident-grid"><label className="incident-field span-3"><span>Subject <b>*</b></span><input maxLength={240} value={form.subject} onChange={e=>update({subject:e.target.value})} placeholder="Brief, searchable summary"/>{errors.subject&&<em>{errors.subject}</em>}</label><label className="incident-field span-3"><span>Description <b>*</b></span><textarea rows={7} maxLength={20000} value={form.description} onChange={e=>update({description:e.target.value})} placeholder="What happened, what did you expect, when did it start, and what troubleshooting has already been tried?"/><small>{form.description.length} / 20,000</small>{errors.description&&<em>{errors.description}</em>}</label><label className="incident-field span-3"><span>Emails to Notify</span><input value={form.emails_to_notify} onChange={e=>update({emails_to_notify:e.target.value})} placeholder="manager@example.com, watcher@example.com"/><small>Separate addresses with commas. Sensitive field values are never inserted automatically.</small>{errors.emails&&<em>{errors.emails}</em>}</label>
   <div className="attachment-drop span-3" onDragOver={e=>e.preventDefault()} onDrop={drop} onClick={()=>fileInput.current?.click()}><input ref={fileInput} hidden multiple type="file" accept=".png,.jpg,.jpeg,.gif,.pdf,.doc,.docx,.xls,.xlsx,.txt,.zip" onChange={e=>addFiles(Array.from(e.target.files||[]))}/><strong>Drag files here or click to browse</strong><span>Up to 10 files, 25 MB each</span>{files.map((file,index)=><button type="button" onClick={event=>{event.stopPropagation();setFiles(files.filter((_,i)=>i!==index))}} key={`${file.name}-${index}`}>{file.name} · {(file.size/1024).toFixed(0)} KB ×</button>)}</div>
   {user.role!=='end_user'&&<details className="resolution-draft span-3"><summary>Technician-only resolution notes</summary><textarea rows={4} value={form.resolution} onChange={e=>update({resolution:e.target.value})} placeholder="Optional working resolution notes. Requesters cannot see this field during creation."/></details>}
  </div></section>
  <footer className="incident-actions"><button type="button" onClick={onCancel}>Cancel</button><button type="button" onClick={()=>{setErrors({});setError('')}}>Clear validation</button><button type="button" onClick={reset}>Reset</button><button type="button" onClick={saveDraft}>Save Draft</button><button className="primary" disabled={busy}>{busy?'Submitting Incident…':'Submit Incident →'}</button></footer>
 </form></section>
}
