"""Packaged Windows entry point for Northstar Desk."""
from __future__ import annotations

import argparse
import base64
import os
import re
import secrets
import shutil
import socket
import subprocess
import sys
import threading
import time
import traceback
import urllib.request
import webbrowser
from pathlib import Path
from urllib.parse import quote, urlsplit


def bundle_root() -> Path:
    return Path(getattr(sys, "_MEIPASS", Path(__file__).resolve().parents[1]))


def quote_env(value: str) -> str:
    return '"' + value.replace("\\", "/").replace('"', '\\"') + '"'


def config_path(data_root: Path) -> Path:
    return data_root / ".env"


def validate_service_ports(
    https_port: int, northstar_port: int, assetpilot_port: int | None = None
) -> None:
    ports = {
        "HTTPS": https_port,
        "Northstar Desk": northstar_port,
    }
    for name, port in ports.items():
        if not 1 <= port <= 65535:
            raise ValueError(f"{name} port must be between 1 and 65535")
    if len(set(ports.values())) != len(ports):
        raise ValueError("HTTPS and Northstar Desk must use different ports")


def https_url(hostname: str, port: int) -> str:
    return f"https://{hostname}" if port == 443 else f"https://{hostname}:{port}"


def write_caddy_config(
    data_root: Path,
    dns_name: str,
    asset_dns_name: str,
    https_port: int,
    northstar_port: int,
    assetpilot_port: int,
) -> None:
    northstar_address = dns_name if https_port == 443 else f"https://{dns_name}:{https_port}"
    (data_root / "Caddyfile").write_text(
        f"""# HTTPS configuration generated by Northstar Desk Setup.
# Caddy's local CA root must be trusted by client computers (normally through Group Policy).
{northstar_address} {{
    tls internal
    encode zstd gzip
    reverse_proxy 127.0.0.1:{northstar_port}
    header {{
        Strict-Transport-Security \"max-age=31536000; includeSubDomains\"
        X-Content-Type-Options \"nosniff\"
        Referrer-Policy \"strict-origin-when-cross-origin\"
    }}
}}
""",
        encoding="utf-8",
    )


def installed_update_public_key() -> str:
    candidate = Path(sys.executable).resolve().parent / "update-public-key.txt"
    if not candidate.is_file():
        return ""
    value = candidate.read_text(encoding="ascii").strip()
    try:
        if len(base64.b64decode(value, validate=True)) != 32:
            return ""
    except ValueError:
        return ""
    return value


def configure_update_trust(data_root: Path, public_key_file: Path) -> None:
    value = public_key_file.read_text(encoding="ascii").strip()
    try:
        if len(base64.b64decode(value, validate=True)) != 32:
            raise ValueError("length")
    except ValueError as exc:
        raise RuntimeError("The update verification public key is invalid.") from exc
    target = config_path(data_root)
    if not target.is_file():
        raise RuntimeError("Northstar Desk must be configured before update trust can be installed.")
    lines = [line for line in target.read_text(encoding="utf-8").splitlines()
             if not line.startswith("ITSM_UPDATE_PUBLIC_KEY=") and not line.startswith("ITSM_UPDATE_STAGING_DIRECTORY=")]
    lines.extend([f"ITSM_UPDATE_PUBLIC_KEY={value}",
                  f"ITSM_UPDATE_STAGING_DIRECTORY={quote_env(str(data_root / 'updates'))}"])
    target.write_text("\n".join(lines) + "\n", encoding="utf-8")
    if os.name == "nt":
        subprocess.run(["icacls.exe", str(target), "/inheritance:r", "/grant:r",
                        "Administrators:(F)", "SYSTEM:(F)"], check=True, stdout=subprocess.DEVNULL)


def activate(data_root: Path) -> None:
    root = bundle_root()
    os.environ["ITSM_CONFIG_FILE"] = str(config_path(data_root))
    os.environ["ITSM_DATA_DIRECTORY"] = str(data_root / "data")
    os.environ["ITSM_STATIC_DIRECTORY"] = str(root / "frontend" / "dist")
    os.chdir(data_root)


def write_local_config(data_root: Path, organization: str, port: int) -> None:
    data_root.mkdir(parents=True, exist_ok=True)
    database = (data_root / "data" / "itsm.db").resolve()
    backup = (data_root / "backups").resolve()
    lines = [
        "ITSM_ENVIRONMENT=evaluation",
        f"ITSM_DATABASE_URL={quote_env('sqlite:///' + database.as_posix())}",
        f"ITSM_SECRET_KEY={secrets.token_urlsafe(48)}",
        "ITSM_COOKIE_SECURE=false",
        f"ITSM_PUBLIC_URL=http://127.0.0.1:{port}",
        f"ITSM_ALLOWED_ORIGINS=http://127.0.0.1:{port},http://localhost:{port}",
        "ITSM_TRUSTED_HOSTS=127.0.0.1,localhost",
        "ITSM_BIND_HOST=127.0.0.1",
        "ITSM_OUTBOUND_EMAIL_ENABLED=false",
        "ITSM_ASSETPILOT_ENABLED=false",
        f"ITSM_PORT={port}",
        f"ITSM_DATA_DIRECTORY={quote_env(str(data_root / 'data'))}",
        f"ITSM_BACKUP_DIRECTORY={quote_env(str(backup))}",
        f"ITSM_SITE_NAME={quote_env(organization or 'Northstar Desk')}",
        "ITSM_ASSETPILOT_URL=http://127.0.0.1:5080",
        "ITSM_ASSETPILOT_INTERNAL_URL=http://127.0.0.1:5080",
        f"ITSM_ASSETPILOT_EXECUTABLE={quote_env(str(Path(os.environ.get('ProgramFiles', 'C:/Program Files')) / 'Northstar Desk' / 'AssetPilot' / 'AssetPilot.exe'))}",
        f"ITSM_ASSETPILOT_DATABASE_PATH={quote_env(str(data_root / 'AssetPilot' / 'Data' / 'assetpilot.db'))}",
    ]
    config_path(data_root).write_text("\n".join(lines) + "\n", encoding="utf-8")


def read_env_file(path: Path) -> dict[str, str]:
    """Read simple KEY=VALUE settings from a Northstar .env file."""
    values: dict[str, str] = {}
    if not path.is_file():
        raise RuntimeError(f"Configuration file was not found: {path}")
    for raw_line in path.read_text(encoding="utf-8").splitlines():
        line = raw_line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, value = line.split("=", 1)
        value = value.strip()
        if len(value) >= 2 and value[0] == '"' and value[-1] == '"':
            value = value[1:-1].replace('\\"', '"')
        values[key.strip()] = value
    return values


GENERATED_PRODUCTION_KEYS = {
    "ITSM_ALLOWED_ORIGINS",
    "ITSM_BACKUP_DIRECTORY",
    "ITSM_BIND_HOST",
    "ITSM_COOKIE_SECURE",
    "ITSM_DATABASE_URL",
    "ITSM_DATA_DIRECTORY",
    "ITSM_ENVIRONMENT",
    "ITSM_FORWARDED_ALLOW_IPS",
    "ITSM_HTTPS_PORT",
    "ITSM_PORT",
    "ITSM_PUBLIC_URL",
    "ITSM_TRUSTED_HOSTS",
    "ITSM_UPDATE_STAGING_DIRECTORY",
}

LOCAL_MACHINE_PATH_KEYS = {
    "ITSM_ASSETPILOT_DATABASE_PATH",
    "ITSM_ASSETPILOT_EXECUTABLE",
}


def imported_production_settings(source_env: Path | None) -> dict[str, str]:
    """Return safe old-server settings to merge into a new-server config.

    The old database URL and machine-local paths are deliberately ignored so a
    restored server never points back at the retired machine.  ``ITSM_SECRET_KEY``
    is preserved because database-stored integration credentials are encrypted
    with it.
    """
    if source_env is None:
        return {}
    source_values = read_env_file(source_env)
    imported: dict[str, str] = {}
    for key, value in source_values.items():
        if not key.startswith("ITSM_"):
            continue
        if key in GENERATED_PRODUCTION_KEYS or key in LOCAL_MACHINE_PATH_KEYS:
            continue
        imported[key] = value
    return imported


def write_production_config(
    data_root: Path,
    organization: str,
    dns_name: str,
    asset_dns_name: str,
    database_host: str,
    database_port: int,
    database_name: str,
    database_user: str,
    database_password: str,
    backup_directory: Path,
    https_port: int = 443,
    northstar_port: int = 8000,
    assetpilot_port: int = 5080,
    source_env: Path | None = None,
) -> None:
    """Create the protected server configuration and pilot HTTPS proxy file."""
    data_root.mkdir(parents=True, exist_ok=True)
    backup_directory.mkdir(parents=True, exist_ok=True)
    imported_settings = imported_production_settings(source_env)
    secret_key = imported_settings.pop("ITSM_SECRET_KEY", secrets.token_urlsafe(48))
    encoded_user = quote(database_user, safe="")
    encoded_password = quote(database_password, safe="")
    database_url = (
        f"postgresql+psycopg://{encoded_user}:{encoded_password}@"
        f"{database_host}:{database_port}/{database_name}"
    )
    validate_service_ports(https_port, northstar_port, assetpilot_port)
    public_url = https_url(dns_name, https_port)
    lines = [
        "ITSM_ENVIRONMENT=production",
        f"ITSM_DATABASE_URL={quote_env(database_url)}",
        f"ITSM_SECRET_KEY={secret_key}",
        "ITSM_SESSION_MINUTES=480",
        "ITSM_COOKIE_SECURE=true",
        f"ITSM_PUBLIC_URL={public_url}",
        f"ITSM_ALLOWED_ORIGINS={public_url}",
        f"ITSM_TRUSTED_HOSTS={dns_name}",
        "ITSM_FORWARDED_ALLOW_IPS=127.0.0.1",
        "ITSM_BIND_HOST=127.0.0.1",
        f"ITSM_PORT={northstar_port}",
        f"ITSM_HTTPS_PORT={https_port}",
        "ITSM_OUTBOUND_EMAIL_ENABLED=false",
        "ITSM_ASSETPILOT_ENABLED=false",
        f"ITSM_DATA_DIRECTORY={quote_env(str(data_root / 'data'))}",
        f"ITSM_BACKUP_DIRECTORY={quote_env(str(backup_directory))}",
        f"ITSM_SITE_NAME={quote_env(organization or 'Northstar Desk')}",
        "ITSM_AGENT_ALLOW_ACCOUNT_NAME_MATCH=true",
        f"ITSM_UPDATE_STAGING_DIRECTORY={quote_env(str(data_root / 'updates'))}",
    ]
    existing_keys = {line.split("=", 1)[0] for line in lines if "=" in line}
    for key in sorted(imported_settings):
        if key not in existing_keys:
            lines.append(f"{key}={quote_env(imported_settings[key])}")
    update_public_key = installed_update_public_key()
    if update_public_key:
        lines.append(f"ITSM_UPDATE_PUBLIC_KEY={update_public_key}")
    target = config_path(data_root)
    target.write_text("\n".join(lines) + "\n", encoding="utf-8")
    write_caddy_config(
        data_root, dns_name, asset_dns_name, https_port, northstar_port, assetpilot_port,
    )


def _replace_keyed_lines(path: Path, replacements: dict[str, str]) -> None:
    lines = path.read_text(encoding="utf-8").splitlines()
    remaining = dict(replacements)
    result: list[str] = []
    for line in lines:
        matched = next((key for key in remaining if line.startswith(key)), None)
        if matched is None:
            result.append(line)
        else:
            result.append(remaining.pop(matched))
    result.extend(remaining.values())
    path.write_text("\n".join(result) + "\n", encoding="utf-8")


def configure_service_ports(
    data_root: Path,
    https_port: int,
    northstar_port: int,
    assetpilot_port: int,
    dns_name: str | None = None,
    asset_dns_name: str | None = None,
) -> None:
    """Change service addresses without rotating credentials or other settings."""
    validate_service_ports(https_port, northstar_port, assetpilot_port)
    target = config_path(data_root)
    if not target.is_file():
        raise RuntimeError("Northstar Desk must be configured before its ports can be changed.")
    values: dict[str, str] = {}
    for line in target.read_text(encoding="utf-8").splitlines():
        if "=" not in line or line.lstrip().startswith("#"):
            continue
        key, value = line.split("=", 1)
        values[key] = value.strip().strip('"')
    northstar_host = dns_name or urlsplit(values.get("ITSM_PUBLIC_URL", "")).hostname
    assetpilot_host = asset_dns_name or "assets.invalid"
    if not northstar_host:
        raise RuntimeError("The existing Northstar Desk DNS name could not be read.")
    public_url = https_url(northstar_host, https_port)
    _replace_keyed_lines(target, {
        "ITSM_PUBLIC_URL=": f"ITSM_PUBLIC_URL={public_url}",
        "ITSM_ALLOWED_ORIGINS=": f"ITSM_ALLOWED_ORIGINS={public_url}",
        "ITSM_TRUSTED_HOSTS=": f"ITSM_TRUSTED_HOSTS={northstar_host}",
        "ITSM_PORT=": f"ITSM_PORT={northstar_port}",
        "ITSM_HTTPS_PORT=": f"ITSM_HTTPS_PORT={https_port}",
    })
    write_caddy_config(
        data_root, northstar_host, assetpilot_host,
        https_port, northstar_port, assetpilot_port,
    )
    print(
        f"Service ports configured: HTTPS {https_port}, Northstar Desk {northstar_port}."
    )


def protect_production_secrets(data_root: Path) -> None:
    """Lock production secrets only after initialization has consumed them.

    Applying these ACLs before Alembic/Pydantic re-read ``.env`` caused the
    packaged configuration command to deny itself access when launched outside
    a SYSTEM token.  The scheduled services run as SYSTEM, so protecting the
    files after successful initialization preserves both usability and the
    intended least-access production posture.
    """
    if os.name != "nt":
        return
    for target in (
        config_path(data_root),
    ):
        if not target.exists():
            continue
        subprocess.run(
            ["icacls.exe", str(target), "/inheritance:r", "/grant:r",
             "Administrators:(F)", "SYSTEM:(F)"],
            check=True,
            stdout=subprocess.DEVNULL,
        )


def provision_postgresql(
    host: str,
    port: int,
    database_name: str,
    service_user: str,
    admin_user: str,
    admin_password: str,
) -> str:
    """Create or repair the least-privilege application role and database."""
    import psycopg
    from psycopg import sql

    service_password = secrets.token_urlsafe(36)
    with psycopg.connect(
        host=host,
        port=port,
        dbname="postgres",
        user=admin_user,
        password=admin_password,
        autocommit=True,
        connect_timeout=10,
    ) as connection:
        role_exists = connection.execute(
            "SELECT 1 FROM pg_roles WHERE rolname = %s", (service_user,)
        ).fetchone()
        if role_exists:
            connection.execute(
                sql.SQL("ALTER ROLE {} WITH LOGIN PASSWORD {}").format(
                    sql.Identifier(service_user), sql.Literal(service_password)
                )
            )
        else:
            connection.execute(
                sql.SQL("CREATE ROLE {} WITH LOGIN PASSWORD {}").format(
                    sql.Identifier(service_user), sql.Literal(service_password)
                )
            )
        database_exists = connection.execute(
            "SELECT 1 FROM pg_database WHERE datname = %s", (database_name,)
        ).fetchone()
        if not database_exists:
            connection.execute(
                sql.SQL("CREATE DATABASE {} OWNER {}").format(
                    sql.Identifier(database_name), sql.Identifier(service_user)
                )
            )
        else:
            connection.execute(
                sql.SQL("ALTER DATABASE {} OWNER TO {}").format(
                    sql.Identifier(database_name), sql.Identifier(service_user)
                )
            )
    return service_password


def ensure_alembic_version_capacity(database_url: str) -> None:
    """Repair legacy Alembic tracking columns before running any revision.

    Alembic's default ``version_num`` column is VARCHAR(32), while this
    application's descriptive revision identifiers can be longer.  This
    preflight is deliberately independent of the current revision so it also
    repairs an installation resuming after revision 0006 was already skipped
    or applied by an older build.
    """
    from sqlalchemy import create_engine, inspect, text

    engine = create_engine(database_url, pool_pre_ping=True)
    try:
        with engine.begin() as connection:
            if connection.dialect.name != "postgresql":
                return
            inspector = inspect(connection)
            if "alembic_version" not in inspector.get_table_names():
                return
            version_column = next(
                (column for column in inspector.get_columns("alembic_version")
                 if column["name"] == "version_num"),
                None,
            )
            current_length = getattr(version_column["type"], "length", None) if version_column else None
            if current_length is not None and current_length < 128:
                connection.execute(text(
                    "ALTER TABLE alembic_version "
                    "ALTER COLUMN version_num TYPE VARCHAR(128)"
                ))
    finally:
        engine.dispose()


def initialize(
    data_root: Path,
    organization: str = "",
    admin_email: str = "",
    admin_password: str = "",
) -> None:
    activate(data_root)
    from alembic import command
    from alembic.config import Config
    from sqlalchemy import select
    from itsm.config import settings

    root = bundle_root()
    ensure_alembic_version_capacity(settings.database_url)
    alembic = Config(str(root / "alembic.ini"))
    alembic.set_main_option("script_location", str(root / "migrations"))
    alembic.set_main_option("sqlalchemy.url", settings.database_url.replace("%", "%%"))
    command.upgrade(alembic, "head")
    if settings.production:
        from itsm.seed import seed_production
        seed_production(organization, admin_email, admin_password)
    else:
        from itsm.seed import seed
        seed()
        if organization or admin_email:
            from itsm.database import SessionLocal
            from itsm.models import Organization, Role, User
            with SessionLocal() as db:
                item = db.scalar(select(Organization).order_by(Organization.id))
                if item and organization:
                    item.name = organization
                admin = db.scalar(select(User).where(User.role == Role.ADMIN).order_by(User.id))
                if admin and admin_email:
                    admin.email = admin_email.strip().lower()
                db.commit()


def open_when_ready(url: str) -> None:
    for _ in range(60):
        try:
            with urllib.request.urlopen(url + "/api/health/ready", timeout=1) as response:
                if response.status == 200:
                    webbrowser.open(url)
                    return
        except Exception:
            time.sleep(0.5)


def serve(data_root: Path, open_browser: bool) -> None:
    activate(data_root)
    from itsm.config import settings
    initialize(data_root)
    from itsm.worker import main as worker_main
    from itsm.main import app
    threading.Thread(target=worker_main, name="northstar-worker", daemon=True).start()
    url = settings.public_url.rstrip("/")
    if open_browser:
        threading.Thread(target=open_when_ready, args=(url,), daemon=True).start()
    import uvicorn
    uvicorn.run(app, host=settings.bind_host, port=settings.port,
                proxy_headers=True, forwarded_allow_ips=settings.forwarded_allow_ips, log_level="info")


def backup_existing_database(data_root: Path) -> Path:
    """Create and verify the pre-upgrade backup using the installed config."""
    activate(data_root)
    from itsm.config import settings
    from itsm.database_ops import create_backup

    backup = create_backup(settings.database_url, Path(settings.backup_directory))
    print(f"Verified pre-upgrade backup: {backup}")
    return backup


def export_migration_package(
    data_root: Path,
    output_path: Path,
    backup_path: Path | None = None,
) -> Path:
    """Create a portable migration package from ProgramData and a verified backup."""
    activate(data_root)
    from itsm.database_ops import create_migration_package

    package = create_migration_package(data_root, output_path, backup_path)
    print(f"Northstar Desk migration package created: {package}")
    print("The package contains configuration secrets. Transfer it securely and delete temporary copies after import.")
    return package


def import_migration_package(data_root: Path, package_path: Path) -> None:
    """Restore a migration package onto this configured server."""
    activate(data_root)
    from itsm.config import settings
    from itsm.database_ops import restore_migration_package

    backup_existing_database(data_root)
    backup = restore_migration_package(package_path, data_root, settings.database_url)
    initialize(data_root)
    protect_production_secrets(data_root)
    print(f"Northstar Desk migration package imported from {backup.name}.")


def restore_configured_backup(data_root: Path, backup_path: Path) -> None:
    """Restore a verified database backup into the configured database."""
    activate(data_root)
    from itsm.config import settings
    from itsm.database_ops import restore_backup

    restore_backup(backup_path, settings.database_url)
    print(f"Database backup restored: {backup_path}")


def copy_restored_data_files(source_data_root: Path, target_data_root: Path) -> None:
    """Copy filesystem data that is not contained in the database dump."""
    copied: list[str] = []
    for relative in ("data/attachments",):
        source = source_data_root / relative
        if not source.is_dir():
            continue
        destination = target_data_root / relative
        destination.parent.mkdir(parents=True, exist_ok=True)
        shutil.copytree(source, destination, dirs_exist_ok=True)
        copied.append(relative)
    if copied:
        print("Copied restored data folders: " + ", ".join(copied))


def check_required_ports(https_port: int, northstar_port: int) -> None:
    """Fail before configuration if another product owns a required port."""
    if https_port == northstar_port:
        raise ValueError("HTTPS and Northstar Desk must use different ports")
    listeners: list[socket.socket] = []
    try:
        for host, port in (
            ("127.0.0.1", northstar_port),
            ("0.0.0.0", https_port),
        ):
            listener = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
            if os.name == "nt":
                listener.setsockopt(socket.SOL_SOCKET, socket.SO_EXCLUSIVEADDRUSE, 1)
            try:
                listener.bind((host, port))
            except OSError as exc:
                listener.close()
                raise RuntimeError(
                    f"Required TCP port {port} is already in use ({exc}). "
                    "Stop the conflicting service and run setup again."
                ) from exc
            listeners.append(listener)
    finally:
        for listener in listeners:
            listener.close()
    print(
        f"Required TCP ports {https_port} and {northstar_port} are available."
    )


def internal_health_request(url: str, public_url: str = "") -> urllib.request.Request:
    """Build an internal probe accepted by production TrustedHostMiddleware."""
    public_host = urlsplit(public_url).hostname
    return urllib.request.Request(
        url, headers={"Host": public_host} if public_host else {}
    )


def wait_for_installed_services(data_root: Path, timeout_seconds: int) -> None:
    """Fail setup only when the core Northstar service is not healthy.

    AssetPilot is an optional integration and must never prevent the service
    desk from installing, starting, authenticating users, or processing work.
    """
    activate(data_root)
    from alembic.config import Config
    from alembic.script import ScriptDirectory
    from sqlalchemy import create_engine, text
    from itsm.config import settings

    root = bundle_root()
    alembic = Config(str(root / "alembic.ini"))
    alembic.set_main_option("script_location", str(root / "migrations"))
    expected = ScriptDirectory.from_config(alembic).get_current_head()
    engine = create_engine(settings.database_url, pool_pre_ping=True)
    try:
        with engine.connect() as connection:
            installed = connection.execute(
                text("SELECT version_num FROM alembic_version")
            ).scalar_one_or_none()
        if installed != expected:
            raise RuntimeError(
                f"Database migration is {installed or 'missing'}; expected {expected}."
            )
    finally:
        engine.dispose()

    public_host = urlsplit(settings.public_url).hostname
    endpoints = {
        "Northstar Desk": (
            f"http://127.0.0.1:{settings.port}/api/health/ready",
            public_host,
        ),
    }
    deadline = time.monotonic() + timeout_seconds
    pending = dict(endpoints)
    last_errors: dict[str, str] = {}
    while pending and time.monotonic() < deadline:
        for name, (url, host_header) in list(pending.items()):
            try:
                request = internal_health_request(
                    url, f"https://{host_header}" if host_header else ""
                )
                with urllib.request.urlopen(request, timeout=2) as response:
                    if response.status == 200:
                        del pending[name]
                        continue
                    last_errors[name] = f"HTTP {response.status}"
            except Exception as exc:
                last_errors[name] = f"{type(exc).__name__}: {exc}"
        if pending:
            time.sleep(1)
    if pending:
        details = "; ".join(
            f"{name} ({last_errors.get(name, 'not ready')})" for name in pending
        )
        raise RuntimeError(f"Installed service readiness failed: {details}")
    try:
        with socket.create_connection(("127.0.0.1", settings.https_port), timeout=3):
            pass
    except OSError as exc:
        raise RuntimeError(
            f"Northstar HTTPS proxy is not listening on TCP {settings.https_port}: {exc}"
        ) from exc
    print("Northstar Desk and its HTTPS proxy are healthy.")


def main() -> int:
    parser = argparse.ArgumentParser(description="Northstar Desk packaged server")
    commands = parser.add_subparsers(dest="command", required=True)
    configure = commands.add_parser("configure-local")
    configure.add_argument("--data-root", type=Path, required=True)
    configure.add_argument("--organization", default="Northstar")
    configure.add_argument("--admin-email", default="admin@example.test")
    configure.add_argument("--port", type=int, default=8000)
    production = commands.add_parser("configure-production")
    production.add_argument("--data-root", type=Path, required=True)
    production.add_argument("--organization", required=True)
    production.add_argument("--admin-email", required=True)
    production.add_argument("--dns-name", required=True)
    production.add_argument("--asset-dns-name", default="assets.invalid")
    production.add_argument("--https-port", type=int, default=443)
    production.add_argument("--northstar-port", type=int, default=8000)
    production.add_argument("--assetpilot-port", type=int, default=5080)
    production.add_argument("--database-host", default="127.0.0.1")
    production.add_argument("--database-port", type=int, default=5432)
    production.add_argument("--database-name", default="northstar_desk")
    production.add_argument("--database-user", default="itsm_service")
    production.add_argument("--database-admin-user", default="postgres")
    admin_password_source = production.add_mutually_exclusive_group(required=True)
    admin_password_source.add_argument("--database-admin-password")
    admin_password_source.add_argument("--database-admin-password-file", type=Path)
    initial_admin_password_source = production.add_mutually_exclusive_group(required=True)
    initial_admin_password_source.add_argument("--initial-admin-password")
    initial_admin_password_source.add_argument("--initial-admin-password-file", type=Path)
    production.add_argument("--backup-directory", type=Path, required=True)
    production.add_argument("--source-config-file", type=Path)
    production.add_argument("--source-data-root", type=Path)
    production.add_argument("--restore-backup", type=Path)
    port_config = commands.add_parser("configure-ports")
    port_config.add_argument("--data-root", type=Path, required=True)
    port_config.add_argument("--https-port", type=int, required=True)
    port_config.add_argument("--northstar-port", type=int, required=True)
    port_config.add_argument("--assetpilot-port", type=int, default=5080)
    port_config.add_argument("--dns-name")
    port_config.add_argument("--asset-dns-name", default="assets.invalid")
    update_trust = commands.add_parser("configure-update-trust")
    update_trust.add_argument("--data-root", type=Path, required=True)
    update_trust.add_argument("--public-key-file", type=Path, required=True)
    migrate = commands.add_parser("migrate")
    migrate.add_argument("--data-root", type=Path, required=True)
    backup = commands.add_parser("backup")
    backup.add_argument("--data-root", type=Path, required=True)
    export_migration = commands.add_parser("export-migration")
    export_migration.add_argument("--data-root", type=Path, required=True)
    export_migration.add_argument("--output", type=Path, required=True)
    export_migration.add_argument("--backup-path", type=Path)
    import_migration = commands.add_parser("import-migration")
    import_migration.add_argument("--data-root", type=Path, required=True)
    import_migration.add_argument("--package", type=Path, required=True)
    import_migration.add_argument("--confirm", required=True)
    readiness = commands.add_parser("wait-ready")
    readiness.add_argument("--data-root", type=Path, required=True)
    readiness.add_argument("--timeout", type=int, default=120)
    port_check = commands.add_parser("check-ports")
    port_check.add_argument("--data-root", type=Path, required=True)
    port_check.add_argument("--https-port", type=int, required=True)
    port_check.add_argument("--northstar-port", type=int, required=True)
    run = commands.add_parser("serve")
    run.add_argument("--data-root", type=Path, required=True)
    run.add_argument("--open-browser", action="store_true")
    args = parser.parse_args()
    # Commands may change the process working directory while activating the
    # selected data root. Resolve every CLI path first so relative paths cannot
    # later point at a different configuration or database.
    for argument, value in vars(args).items():
        if isinstance(value, Path):
            setattr(args, argument, value.resolve())
    if args.command == "configure-local":
        if not 1024 <= args.port <= 65535:
            parser.error("port must be between 1024 and 65535")
        write_local_config(args.data_root, args.organization, args.port)
        initialize(args.data_root, args.organization, args.admin_email)
        print("Northstar Desk local evaluation configured successfully.")
        return 0
    if args.command == "configure-update-trust":
        configure_update_trust(args.data_root, args.public_key_file)
        print("Northstar Desk update verification trust configured successfully.")
        return 0
    if args.command == "backup":
        backup_existing_database(args.data_root)
        return 0
    if args.command == "export-migration":
        export_migration_package(args.data_root, args.output, args.backup_path)
        return 0
    if args.command == "import-migration":
        if args.confirm != "IMPORT":
            raise RuntimeError("Migration import refused; --confirm must be exactly IMPORT")
        import_migration_package(args.data_root, args.package)
        return 0
    if args.command == "configure-ports":
        try:
            configure_service_ports(
                args.data_root, args.https_port, args.northstar_port, args.assetpilot_port,
                args.dns_name, args.asset_dns_name,
            )
        except ValueError as exc:
            parser.error(str(exc))
        return 0
    if args.command == "check-ports":
        try:
            check_required_ports(
                args.https_port, args.northstar_port,
            )
        except ValueError as exc:
            parser.error(str(exc))
        return 0
    if args.command == "migrate":
        initialize(args.data_root)
        print("Northstar Desk database migration completed successfully.")
        return 0
    if args.command == "wait-ready":
        if not 10 <= args.timeout <= 600:
            parser.error("timeout must be between 10 and 600 seconds")
        wait_for_installed_services(args.data_root, args.timeout)
        return 0
    if args.command == "configure-production":
        if not 1 <= args.database_port <= 65535:
            parser.error("database port must be between 1 and 65535")
        try:
            validate_service_ports(
                args.https_port, args.northstar_port, args.assetpilot_port,
            )
        except ValueError as exc:
            parser.error(str(exc))
        for label, value in (("database name", args.database_name), ("database user", args.database_user)):
            if not re.fullmatch(r"[A-Za-z_][A-Za-z0-9_-]{0,62}", value):
                parser.error(f"{label} must start with a letter or underscore and contain only letters, numbers, underscores, or hyphens")
        admin_password = args.database_admin_password
        if args.database_admin_password_file:
            admin_password = args.database_admin_password_file.read_text(encoding="utf-8").rstrip("\r\n")
        if not admin_password:
            parser.error("PostgreSQL administrator password must not be empty")
        initial_admin_password = args.initial_admin_password
        if args.initial_admin_password_file:
            initial_admin_password = args.initial_admin_password_file.read_text(encoding="utf-8").rstrip("\r\n")
        if not initial_admin_password:
            parser.error("Initial Northstar administrator password must not be empty")
        if args.restore_backup and not args.source_config_file:
            parser.error("--source-config-file is required when --restore-backup is used so encrypted integration credentials remain readable")
        database_password = provision_postgresql(
            args.database_host,
            args.database_port,
            args.database_name,
            args.database_user,
            args.database_admin_user,
            admin_password,
        )
        write_production_config(
            args.data_root,
            args.organization,
            args.dns_name,
            args.asset_dns_name,
            args.database_host,
            args.database_port,
            args.database_name,
            args.database_user,
            database_password,
            args.backup_directory,
            args.https_port,
            args.northstar_port,
            args.assetpilot_port,
            args.source_config_file,
        )
        try:
            if args.restore_backup:
                restore_configured_backup(args.data_root, args.restore_backup)
                if args.source_data_root:
                    copy_restored_data_files(args.source_data_root, args.data_root)
                initialize(args.data_root)
            else:
                initialize(
                    args.data_root, args.organization, args.admin_email,
                    initial_admin_password,
                )
        except Exception:
            # Never leave a configuration containing a database password after a
            # failed prerequisite/connection test.
            config_path(args.data_root).unlink(missing_ok=True)
            raise
        protect_production_secrets(args.data_root)
        print("Northstar Desk production server configured successfully.")
        return 0
    serve(args.data_root, args.open_browser)
    return 0


if __name__ == "__main__":
    try:
        raise SystemExit(main())
    except SystemExit:
        raise
    except Exception:
        details = traceback.format_exc()
        try:
            data_root_index = sys.argv.index("--data-root") + 1
            diagnostic_root = Path(sys.argv[data_root_index]).resolve()
            diagnostic_root.mkdir(parents=True, exist_ok=True)
            (diagnostic_root / "setup-error.log").write_text(details, encoding="utf-8")
        except Exception:
            pass
        print(details, file=sys.stderr)
        raise SystemExit(1)
